* Deliverable
  - Edit: https://stackblitz.com/edit/github-tefdaa
  - Page: [[https://github-tefdaa.stackblitz.io]]
* Requirement
  1) Reusable Toolbar Component
  2) Drop down selector (E.G. selecting a font)
  3) A button with state (E.G. a "Bold" button)
  4) A group of buttons that only allow one to be selected (E.G. left / center / right align)
  5) A button that links to another URL location
  6) Configurable by editing a JSON file
  7) Ability to extend to act on the page down the line
* Summary
  - All required elements are grouped inside toolbar and displayed on the page properly, using components from [[https://ng-bootstrap.github.io/#/components/alert/examples][ngbootstrap]] [4/4][100%]
	+ [X] Drop down, selector; under ./src/app/drop-down/
	+ [X] Button with state; under ./src/app/state-button/
	+ [X] Group of buttons that only allow one to be selected; under ./src/app/radio-buttons/
	+ [X] Button that links to another URL location; under ./src/app/url-button/
  - Configurable by edit a JSON file at ./src/app/toolbar/toolbarConfig.json
	+ dropDown
	  1) .dropDown.title: text that display before clicking
	  2) .dropDown.selectors: array of selectors to display after clicking
	  3) .dropDown.selectors.text: text of selectors
    + stateButton
	  1) .title: text display on the button
	+ radioButtons
	  1) .radioButtons: array of buttons to display in the button group
	  2) .radioButtons.title: text to display on the button
	  3) .radioButtons.value: value that get passed when clicked (default to .title for now)
    + urlButtons
	  1) .urlButtons.title: text to display on the button
	  2) .urlButtons.url: url that the button links to
  - Ability to add more than one of each kind of child component
	+ Add another array element inside toolbarItems inside toolbarConfig.json
	+ Toolbar HTML template will use [ngSwitch] and *ngSwitchCase to render all the elements in toolbar as specified in config
	+ This capability is demonstrated by the two state-buttons that toggles bold/italicized; or the two url-buttons that link to different places.
  - Reusability
	+ Json file should *only* store view information (what you can see), not any application logic
	+ All the onClick event of the child components (dropdown, button, radio) are extracted onto parent components
	  1) The above is accomplished using Angular's Output and EventEmitter
	  2) Whenever components got clicked, a message will be sent from the parent (toolbar) to show control over the event on the higher level
	+ Great usability because state and application logic can be configured in the toolbar component alone without touching any child components
  - Extensibility
	+ Since all onClick events can be configure in the top toolbar component, extending toolbar to act on the page is easy: just replace console.log line with code that wants executed
	+ Demonstrated by how toolbar can act on a sibling component: ./src/app/simple-text; text toggles bold/italicized whenever corresponding state-button is clicked.
* Improvements
** Problems
   1) Repeating code in if-else statement; [[file:src/app/toolbar/toolbar.component.ts::button_onClicked(button_state:%20boolean)%20{][toolbar.component.ts]]
   2) Using camelCase in place of snake_case project-wide
   3) Module reuse with [[https://angular.io/api/common/NgSwitch][NgSwitch]] in toolbar.component.html
   4) Remove all console.log debug codes project-wide
   5) Read [[https://angular.io/guide/styleguide][Angular Style Guide]]
** Correction Logs
*** Problem 1: Move .emit call out of if-else scope
#+begin_src typescript
  button_onClicked(button_state: boolean) {
    if (button_state) {
      console.log("button clicked");
    } else {
      console.log("button unclicked");
    }
    this.bold_event.emit(button_state);
  }
#+end_src
	Removing

*** Problem 2: Use camelCase instead of snake_case project-wide
	1) configToolbar.json file
	2) Most changes are made in toolbar.component.ts/html
	3) Minor changes are made in toolbar's child components
	4) Also refactor some naming convention for @Output() and EventHandler
*** Problem 3: A way to add more than one of each kind of element.
	1) Redesign json configure file; add "type" properties
	   #+begin_src typescript
  {
	  "toolbarItems": [
		  {
			  "type": "urlButton",
			  "config": {
				  "title": "Stackblitz Editor",
				  "url": "https://google.com/"
			  }
		  }
  ...
  }
	   #+end_src
	2) Add [ngSwitch] and *ngSwitchCase in toolbar.component.html template
	   #+begin_src html
<ng-container *ngFor="let item of items" [ngSwitch]="item.type">
  <app-drop-down
	*ngSwitchCase="'dropDown'"
	[config]="item.config"
	(onClickEvent)="onDropDownClick($event, item)">
  </app-drop-down>
  <app-state-button
	*ngSwitchCase="'stateButton'"
	[config]="item.config"
	(onClickEvent)="onButtonClick($event, item)">
  </app-state-button>
  <app-radio-buttons
	*ngSwitchCase="'radioButtons'"
	[config]="item.config"
	(onClickEvent)="onRadioClick($event, item)">
  </app-radio-buttons>
  <app-url-button
	*ngSwitchCase="'urlButton'"
	[config]="item.config">
  </app-url-button>
</ng-container>
	   #+end_src
	3) onClick Event Handler will take an extra parameter "item"; so that we know which element is clicked
    4) The above is demonstrated by adding another state-button "Italicized"
	   #+begin_src typescript
  onButtonClick(buttonState: boolean, item: any) {
    console.log("state button got clicked");
    console.log(item.config.title);
    switch (item.config.title) {
      case "bold":
        console.log("inside bold event emitter");
        this.boldEvent.emit(buttonState);
        break;
      case "italicized":
        console.log("inside ital event emitter");
        this.italicizedEvent.emit(buttonState);
    }
    console.log(item.config.title);
  }

	   #+end_src
*** Problem 4: Delete all console.log
* Logs
** Set up ng-boostrap
  1) Install ng-bootstrap
	 #+begin_src shell
	 npm install --save @ng-bootstrap/ng-bootstrap
	 #+end_src
  2) Import to main module
	 #+LOCATION: ./src/app/app.module.ts
	 #+begin_src javascript
	   import {NgbModule} from '@ng-bootstrap/ng-bootstrap';

	   @NgModule({
		 ...
		 imports: [NgbModule, ...],
		 ...
	   })
	   export class YourAppModule {
	   }
	 #+end_src
  3) Add Bootstrap CSS
	 - Install through npm
	   #+begin_src shell
		 npm install --save bootstrap
   	   #+end_src
	 - Import in app
	   #+LOCATION: ./src/styles.css
	   #+begin_src css
		 @import "~bootstrap/dist/css/bootstrap.css";
	   #+end_src

** Navi + Drop-down Experiment
   1) Create drop-down component
   2) Copy and Paste html from ng-bootstrap [[https://ng-bootstrap.github.io/#/components/dropdown/examples][dropdown site]]
   3) Create tool-bar component
   4) Incorporate drop-down in toolbar html template
   5) Everything shows. Now how do we configure this drop-down effectively from toolbar?
** Dropdown Customization
*** Goal
   1) Aim is to customize the selectors inside Drop-down
   2) Approach: @input or encode all customization in
*** @input approach (hard-coded)
	1) Add @Input() in drop-down class & Use it in HTML template {{option}}
	   #+begin_src typescript
		 @Input() option: String
	   #+end_src
	2) Pass parameter down from Toolbar (Parent Component)
	   #+begin_src html
		 <app-drop-down [option]="'seek'"></app-drop-down>
	   #+end_src
	3) More general, pass down an array declared and defined in Toolbar.ts (Parent)
	   #+begin_src javascript
		 selectors: string[] = ['Test1', 'Test2', 'Test2']
	   #+end_src
	   #+begin_src html
		 <app-drop-down [selectors]="selectors"></app-drop-down>
	   #+end_src
	4) Add *ngFor to iterate through array in drop-down.html
	   #+begin_src html
		 <button *ngFor="let selector of selectors" ngbDropdownItem>{{selector}}</button>
	   #+end_src
*** @json approach (configuration-file)
	1) Import config.json file in toolbar
	   #+begin_src javascript
		 import * as config from './toolbar_config.json';
	   #+end_src
	2) Add compiler option in tsconfig.json for parsing json
	   #+begin_src javascript
		 {
			 "compileroptions": {
				 "resolvejsonmodule": true,
				 "esmoduleinterop": true,
				 "allowsyntheticdefaultimports": true
			 }
		 }
	   #+end_src
	3) Pass configuration down from toolbar to drop-down
	   #+begin_src typescript
		   dropdown_config: any = config.dropdown
		 // In html template
		   <app-drop-down [title]="dropdown_config.title" [selectors]="dropdown_config.selectors"></app-drop-down>
	   #+end_src
    4) Adjust accordingly in drop-down component

** State Button
*** Goal
	1) Get clickable button on the page
	2) Pass in onClick function from Parent (toolbar) for state change
	   + For starter, a function that just shows pop up messages when clicked
	3) configure.json that configure the button's display text (e.g. Bold / Italics)jjj
*** Get button on page
	1) Add associated html template in button, copy from [[https://ng-bootstrap.github.io/#/components/buttons/examples][bootstrap Angular Site]]
	   #+begin_src html
		 <label class="btn-primary" ngbButtonLabel>
		   <input type="checkbox" ngbButton [(ngModel)]="state"> Bold
		 </label>
	   #+end_src
	2) "Can't bind to ngModel error": Import Form modules per instruction from [[https://angular.io/tutorial/toh-pt1][Angular Tutorial Site]]
	   #+LOCATION: app.module.ts
	   #+begin_src typescript
		 import { FormsModule } from '@angular/forms'; // <-- NgModel lives here
		 // Add it to @NgModule metadata's imports array
		 imports: [
		   BrowserModule,
		   FormsModule
		 ],
	   #+end_src
*** Add onClick() method, to catch state change when clicked
	#+begin_src typescript
	  export class StateButtonComponent implements OnInit {
	  state: boolean = false;
	  onSelect(): void {
		  console.log(this.state);
	  }
	  }
	  // Add (click) directive in html template
	  <input [(ngModel)]="state" (click)="onSelect()" type="checkbox" ngbButton> Bold
	#+end_src

*** Extract click event to Parent Component, to make state-button "dumb"
	1) Research and Learn EventEmitter and Output directive according to this [[https://angular.io/guide/component-interaction#parent-listens-for-child-event][Angular tutorial]]
	2) Import EventEmitter & Output, then use them in child component
	   #+LOCATION: state-button.component.ts
	   #+begin_src typescript
		 import { Component, OnInit, EventEmitter, Output } from '@angular/core';
		 export class StateButtonComponent implements OnInit {
		   @Input() title: string;
		   @Output() clicked = new EventEmitter<boolean>();
		   state: boolean = false;
		   onSelect(): void {
			 console.log(this.state);
			 this.clicked.emit(!this.state);
		   }
	   #+end_src
    3) Configuration in Parent component
	   #+begin_src typescript
		 button_onClicked(button_state: boolean) {
		   if (button_state) {
			 console.log("button clicked");
		   } else {
			 console.log("button unclicked");
		   }
		 }
		 // In HTML template
		 <app-state-button (clicked)="button_onClicked($event)"></app-state-button>
	   #+end_src

*** Configure.json for state button
	1) Text display on the button
	   #+begin_src typescript
		 {
		   "state_button": {
			 "title": "Bold"
		   }
		 }
	   #+end_src
    2) Adjust parent and child component accordingly to incorporate customization

*** Extract DropdownEvent to be handled in toolbar (parent)
	- Similar procedures as State-button or Radio
** Radio Buttons
*** Goals
	1) Hardcode arbitrary Radio Buttons so that it appears on the page

	2) Extract onClick() event to Parent (toolbar)

	3) Implement configuration from Json, that controls the text on each radio buttons, and arbitrary# of them
*** Radio Buttons Hard Code
	1) Copy code from [[https://ng-bootstrap.github.io/#/components/buttons/examples][Angular Bootstrap Radio Button]]
	   #+begin_src typescript
		 // In TS
		 export class RadioButtonsComponent implements OnInit {
		   model: any = 1;
		   constructor() { }

		   ngOnInit() {
		   }
		 // In HTML template
		 <div class="btn-group btn-group-toggle" ngbRadioGroup name="radioBasic" [(ngModel)]="model">
		   <label ngbButtonLabel class="btn-light">
			 <input ngbButton type="radio" [value]="1"> Left (pre-checked)
		   </label>
		   <label ngbButtonLabel class="btn-light">
			 <input ngbButton type="radio" value="middle"> Middle
		   </label>
		   <label ngbButtonLabel class="btn-light">
			 <input ngbButton type="radio" [value]="false"> Right
		   </label>
		 </div>
	   #+end_src
*** Extract onClick event to Parent
	#+LOCATIONS: radio-buttons
	#+begin_src typescript
	  import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
	  export class RadioButtonsComponent implements OnInit {
		@Input() config: any;
		@Output() clicked = new EventEmitter<string>();
		model: any;
		onClick(value: string): void {
		  console.log(value);
		  this.clicked.emit(value);
		}
	  }
	  // HTML
	  <label *ngFor="let button of config" ngbButtonLabel class="btn-light">
	    <input (click)="onClick(button.value)" ngbButton type="radio" [value]="button.value"> {{button.title}}
	  </label>
	#+end_src
	#+LOCATIONS: toolbar
	#+begin_src typescript
	  radio_onClicked(value: string) {
		console.log(value);
		}
	  // HTML
		<app-radio-buttons [config]="radio_buttons_config" (clicked)="radio_onClicked($event)"></app-radio-buttons>
	#+end_src
*** Configuration from Json
	1) Json structure design
	   #+begin_src typescript
		 radio_buttons_config: any = config.radio_buttons;
		 "radio_buttons": [
			 {
				 "title": "left",
				 "value": "left"
			 },
			 {
				 "title": "middle",
				 "value": "middle"
			 },
			 {
				 "title": "right",
				 "value": "right"
			 }
		 ]
	   #+end_src
** URL Button
*** Goals
	1) Create Component and Hardcode the link in
	2) Implement configuration where it link to
*** Hardcode button
	1) Use bootstrap button and make url a variable
	   #+begin_src typescript
		 @Input() url: string = "https://kinchang.com";
		 <a class="btn btn-outline-dark" href={{url}} role="button">Link</a>
	   #+end_src
    2) Json configuration
	   1) Json structure
		  #+begin_src typescript
			{
				"url_button": {
					"title": "My portfolio",
					"url": "https://kinchang.com/"
				}
			}
		  #+end_src
	   2) Pass it down to child
		  #+begin_src typescript
			url_button_config: any = config.url_button;
			// In url-button ts
			@Input() config: any = { "title": "Link", "url": "https://google.com/" };
			// HTML template
			<a class="btn btn-outline-dark" href={{config.url}} role="button">{{config.title}}</a>
		  #+end_src
** Create simple component, that can be changed by toolbar
*** Goals
	1) Demonstrate how toolbar can be used to act on sibling component in the app
	2) Create a simple text area
* Some key insights
  - Some criterion for Re-usable components?
	1) Should consist mostly dumb components, with no application logic
  - How generalize should I make this toolbar?
	1) Drop-down
	   - # of selectors
	   - Name of selectors (Helvetica, Times New Roman, etc.)
	   - title of the dropdown (Select Font)
	   - Maybe configure action function in the future?
	   - Answers: configure.json should only be used for data-related configuration, no app logic should be included
    2) Action function should always be extract to the toolbar Parent component for easy configuration
	   - Make most components as dumb as possible
	   - Concentrate all the logics in the root component (Toolbar)
* Resource
  - [[https://ng-bootstrap.github.io/#/home][Angular Powered Bootstrap]]
  - [[https://angular.io/tutorial][Angular Tour-of-Hero Tutorial]]
  - [[https://getbootstrap.com/docs/4.3/getting-started/introduction/][Bootstrap 4 Documentation]]
  - [[https://angular.io/guide/component-interaction#parent-listens-for-child-event][Angular Listen for Child Element]]
** Stackblitz Deployment
  - [[https://stackblitz.com/github/ckwojai/toolbar-challenge/tree/config_refactor][Stackblitz refactor_config branch]]
  - https://stackblitz.com/edit/github-tjfvrs-rwmi16
  - [[https://stackblitz.com/edit/github-tefdaa][Stackblitz Master Branch]]

* Ideas
  1) Toolbar component, integrating bunch of umbrella smaller component satisfying the above requirements
  2) Toolbar component, with everything implemented in itself
  3) End results
  4) How generalize should it be?
  5) Create library so everybody can use it
  6) Need to brush up on Angular Databinding Syntax, [], (), [()]
